/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.unitec.mini.windows.apps;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author leonel
 */
public class FinderApp extends javax.swing.JInternalFrame  implements AppInterface{
    int mouseX, mouseY;
  
    public FinderApp() {
        initComponents();
        setComponents();
    }

    public void setComponents(){
        ImageIcon appIcon = new ImageIcon(getClass().getResource("/images/icon_finder_20.png"));
        this.setFrameIcon(appIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu_Finder_Options = new javax.swing.JPopupMenu();
        jMenuItem_new_folder = new javax.swing.JMenuItem();
        jPanel_Finder = new javax.swing.JPanel();
        jPanel_Sidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel_Top_bar = new javax.swing.JPanel();
        jButton_New_Folder = new javax.swing.JButton();
        jPanel_Path_bar = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton_Home_Folder = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel_Finder_Dashboard = new javax.swing.JPanel();

        jMenuItem_new_folder.setText("New folder");
        jMenuItem_new_folder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_new_folderActionPerformed(evt);
            }
        });
        jPopupMenu_Finder_Options.add(jMenuItem_new_folder);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Finder");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Finder.setBackground(new java.awt.Color(255, 255, 51));
        jPanel_Finder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_FinderMousePressed(evt);
            }
        });

        jLabel1.setText("Places");

        jScrollPane2.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel_SidebarLayout = new javax.swing.GroupLayout(jPanel_Sidebar);
        jPanel_Sidebar.setLayout(jPanel_SidebarLayout);
        jPanel_SidebarLayout.setHorizontalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_SidebarLayout.setVerticalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_New_Folder.setText("New Folder");

        javax.swing.GroupLayout jPanel_Top_barLayout = new javax.swing.GroupLayout(jPanel_Top_bar);
        jPanel_Top_bar.setLayout(jPanel_Top_barLayout);
        jPanel_Top_barLayout.setHorizontalGroup(
            jPanel_Top_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Top_barLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_New_Folder)
                .addGap(16, 16, 16))
        );
        jPanel_Top_barLayout.setVerticalGroup(
            jPanel_Top_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Top_barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_New_Folder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_Home_Folder.setText("Home");

        javax.swing.GroupLayout jPanel_Path_barLayout = new javax.swing.GroupLayout(jPanel_Path_bar);
        jPanel_Path_bar.setLayout(jPanel_Path_barLayout);
        jPanel_Path_barLayout.setHorizontalGroup(
            jPanel_Path_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Path_barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Home_Folder, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel_Path_barLayout.setVerticalGroup(
            jPanel_Path_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Path_barLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Path_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Home_Folder))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Finder_Dashboard.setBackground(new java.awt.Color(0, 255, 0));
        jPanel_Finder_Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_Finder_DashboardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Finder_DashboardLayout = new javax.swing.GroupLayout(jPanel_Finder_Dashboard);
        jPanel_Finder_Dashboard.setLayout(jPanel_Finder_DashboardLayout);
        jPanel_Finder_DashboardLayout.setHorizontalGroup(
            jPanel_Finder_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        jPanel_Finder_DashboardLayout.setVerticalGroup(
            jPanel_Finder_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel_Finder_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel_Finder_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_FinderLayout = new javax.swing.GroupLayout(jPanel_Finder);
        jPanel_Finder.setLayout(jPanel_FinderLayout);
        jPanel_FinderLayout.setHorizontalGroup(
            jPanel_FinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FinderLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel_FinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_FinderLayout.createSequentialGroup()
                        .addComponent(jPanel_Sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel_FinderLayout.createSequentialGroup()
                        .addGroup(jPanel_FinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel_Path_bar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_Top_bar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel_FinderLayout.setVerticalGroup(
            jPanel_FinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FinderLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel_Top_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel_Path_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel_FinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Finder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_Finder_DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_Finder_DashboardMouseClicked
        if(SwingUtilities.isRightMouseButton(evt)){
            mouseX = evt.getX();
            mouseY = evt.getY();
            jPopupMenu_Finder_Options.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jPanel_Finder_DashboardMouseClicked

    private void jPanel_FinderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_FinderMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel_FinderMousePressed

    private void jMenuItem_new_folderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_new_folderActionPerformed
        String folderName = JOptionPane.showInputDialog(null, "Folder name");
        createFolder(folderName, mouseX, mouseY, "Main");
    }//GEN-LAST:event_jMenuItem_new_folderActionPerformed
    
    private void createFolder(String folderName, int posX, int posY, String belongsTo) {
        
    }
    @Override
    public void closeFrame() {
        try {
            this.setClosed(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Home_Folder;
    private javax.swing.JButton jButton_New_Folder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem_new_folder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Finder;
    private javax.swing.JPanel jPanel_Finder_Dashboard;
    private javax.swing.JPanel jPanel_Path_bar;
    private javax.swing.JPanel jPanel_Sidebar;
    private javax.swing.JPanel jPanel_Top_bar;
    private javax.swing.JPopupMenu jPopupMenu_Finder_Options;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
