/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.unitec.mini.windows.apps;

import com.unitec.mini.windows.logic.FileSystemStructure;
import com.unitec.mini.windows.logic.User;
import java.awt.Component;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JTree;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;
import com.unitec.mini.windows.logic.FolderStructureCreator;
import java.nio.file.Paths;

/**
 *
 * @author leonel
 */
public class FinderApp extends JInternalFrame implements AppInterface {

    private int mouseX, mouseY;
    private User userAuthen;
    private FileSystemStructure.FileNode root = null;
    private DefaultTreeModel treeModel;
    private String defaultFoldertPath = "Desktop";

    public FinderApp(User user) {
        this.userAuthen = user;

        initComponents();
        setComponents();
    }

    public void setComponents() {
        ImageIcon appIcon = new ImageIcon(getClass().getResource("/images/icon_finder_20.png"));
        this.setFrameIcon(appIcon);

        try {
            DefaultMutableTreeNode root = FileSystemStructure.getFolderTreeNode(userAuthen.getUsername());
            treeModel = new DefaultTreeModel(root);
            jTree_Folder_Strcture.setModel(treeModel);
            jTree_Folder_Strcture.setCellRenderer(getDirectoryCellRenderer());
            expandTree(jTree_Folder_Strcture);

            jTextField_Path.setText(Paths.get("Users", userAuthen.getUsername(), defaultFoldertPath).toString());

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public DefaultTreeCellRenderer getDirectoryCellRenderer() {
        return new DefaultTreeCellRenderer() {
            @Override
            public Component getTreeCellRendererComponent(JTree tree, Object value, boolean sel, boolean expanded, boolean leaf, int row, boolean hasFocus) {
                super.getTreeCellRendererComponent(tree, value, sel, expanded, leaf, row, hasFocus);

                DefaultMutableTreeNode node = (DefaultMutableTreeNode) value;

                boolean isFolder = node.getAllowsChildren();
                Icon icon = isFolder ? getFileTypeIcon(node.toString(), isFolder) : getFileTypeIcon(node.toString(), isFolder);
                if (icon != null) {
                    setIcon(icon);
                }

                return this;
            }
        };
    }

    private static Icon getFileTypeIcon(String fileName, boolean isFolder) {
        if (isFolder) {
            return UIManager.getIcon("FileView.directoryIcon");
        }

        String extension = fileName.substring(fileName.lastIndexOf('.') + 1).toLowerCase();
        switch (extension) {
            case "txt":
                return UIManager.getIcon("FileView.fileIcon");
            case "jpg":
            case "jpeg":
            case "png":
            case "gif":
                return UIManager.getIcon("FileView.fileIcon");
            default:
                return UIManager.getIcon("FileView.fileIcon");
        }
    }

    private static void expandTree(JTree tree) {
        TreeNode root = (TreeNode) tree.getModel().getRoot();
        for (int i = 0; i < root.getChildCount(); i++) {
            TreeNode child = root.getChildAt(i);
            tree.expandPath(new TreePath(new Object[]{root, child}));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu_Finder_Options = new javax.swing.JPopupMenu();
        jMenuItem_new_folder = new javax.swing.JMenuItem();
        jPanel_Finder = new javax.swing.JPanel();
        jPanel_Sidebar = new javax.swing.JPanel();
        jLabel_Sidebar_Places = new javax.swing.JLabel();
        jScrollPane_Folder_Structure = new javax.swing.JScrollPane();
        jTree_Folder_Strcture = new javax.swing.JTree();
        jPanel_Finder_Dashboard = new javax.swing.JPanel();
        jPanel_Top_Panel = new javax.swing.JPanel();
        jPanel_Top_bar = new javax.swing.JPanel();
        jButton_New_Folder = new javax.swing.JButton();
        jPanel_Path_bar = new javax.swing.JPanel();
        jTextField_Path = new javax.swing.JTextField();
        jButton_Go_To_Home_Folder = new javax.swing.JButton();

        jMenuItem_new_folder.setText("New folder");
        jMenuItem_new_folder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_new_folderActionPerformed(evt);
            }
        });
        jPopupMenu_Finder_Options.add(jMenuItem_new_folder);

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Finder");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Finder.setBackground(new java.awt.Color(255, 255, 51));
        jPanel_Finder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel_FinderMousePressed(evt);
            }
        });

        jLabel_Sidebar_Places.setText("Places");

        jScrollPane_Folder_Structure.setViewportView(jTree_Folder_Strcture);

        javax.swing.GroupLayout jPanel_SidebarLayout = new javax.swing.GroupLayout(jPanel_Sidebar);
        jPanel_Sidebar.setLayout(jPanel_SidebarLayout);
        jPanel_SidebarLayout.setHorizontalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel_Sidebar_Places)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addComponent(jScrollPane_Folder_Structure, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_SidebarLayout.setVerticalGroup(
            jPanel_SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SidebarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel_Sidebar_Places)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane_Folder_Structure, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_Finder_Dashboard.setBackground(new java.awt.Color(0, 255, 0));
        jPanel_Finder_Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_Finder_DashboardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Finder_DashboardLayout = new javax.swing.GroupLayout(jPanel_Finder_Dashboard);
        jPanel_Finder_Dashboard.setLayout(jPanel_Finder_DashboardLayout);
        jPanel_Finder_DashboardLayout.setHorizontalGroup(
            jPanel_Finder_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
        );
        jPanel_Finder_DashboardLayout.setVerticalGroup(
            jPanel_Finder_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        jPanel_Top_bar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_New_Folder.setText("New Folder");
        jButton_New_Folder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_New_FolderActionPerformed(evt);
            }
        });
        jPanel_Top_bar.add(jButton_New_Folder, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 6, -1, -1));

        jTextField_Path.setEditable(false);
        jTextField_Path.setAutoscrolls(false);

        jButton_Go_To_Home_Folder.setText("Home");

        javax.swing.GroupLayout jPanel_Path_barLayout = new javax.swing.GroupLayout(jPanel_Path_bar);
        jPanel_Path_bar.setLayout(jPanel_Path_barLayout);
        jPanel_Path_barLayout.setHorizontalGroup(
            jPanel_Path_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Path_barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Go_To_Home_Folder, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jTextField_Path, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel_Path_barLayout.setVerticalGroup(
            jPanel_Path_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Path_barLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Path_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Go_To_Home_Folder))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Top_bar.add(jPanel_Path_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel_Top_PanelLayout = new javax.swing.GroupLayout(jPanel_Top_Panel);
        jPanel_Top_Panel.setLayout(jPanel_Top_PanelLayout);
        jPanel_Top_PanelLayout.setHorizontalGroup(
            jPanel_Top_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Top_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Top_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_Top_PanelLayout.setVerticalGroup(
            jPanel_Top_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Top_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Top_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_FinderLayout = new javax.swing.GroupLayout(jPanel_Finder);
        jPanel_Finder.setLayout(jPanel_FinderLayout);
        jPanel_FinderLayout.setHorizontalGroup(
            jPanel_FinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FinderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_FinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_FinderLayout.createSequentialGroup()
                        .addComponent(jPanel_Sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel_Finder_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addComponent(jPanel_Top_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_FinderLayout.setVerticalGroup(
            jPanel_FinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FinderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Top_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_FinderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Finder_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Finder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_Finder_DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_Finder_DashboardMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            mouseX = evt.getX();
            mouseY = evt.getY();
            jPopupMenu_Finder_Options.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jPanel_Finder_DashboardMouseClicked

    private void jPanel_FinderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_FinderMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel_FinderMousePressed

    private void jMenuItem_new_folderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_new_folderActionPerformed
        String folderName = JOptionPane.showInputDialog(null, "Folder name");
        createFolder(folderName, mouseX, mouseY, "Main");
    }//GEN-LAST:event_jMenuItem_new_folderActionPerformed

    private void jButton_New_FolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_New_FolderActionPerformed
        try {

            JPanel panel = new JPanel();
            panel.add(new JLabel("Folder name"));
            JTextField input = new JTextField(10);
            panel.add(input);

            int result = JOptionPane.showOptionDialog(null,
                    panel,
                    "New Folder",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    new String[]{"Create", "Cancel"},
                    null
            );

            if (result == JOptionPane.OK_OPTION) {
                String folderName = input.getText().trim();
                if (folderName != null && !folderName.isEmpty()) {

                    // position is irrelevant in this case find other way.
                    int x, y;
                    x = y = 0;

                    Object button = FolderStructureCreator.createButtonFolderAtPosition(
                            userAuthen.getUsername(),
                            defaultFoldertPath,
                            folderName,
                            x,
                            y
                    );

                    if (button != null) {
                        
                    }else {
                        JOptionPane.showMessageDialog(this, 
                                "An error occur creating a folder.", 
                                "Error", 
                                JOptionPane.ERROR_MESSAGE
                        );
                    }
                }
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton_New_FolderActionPerformed

    private void createFolder(String folderName, int posX, int posY, String belongsTo) {

    }

    @Override
    public void closeFrame() {
        try {
            this.setClosed(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Go_To_Home_Folder;
    private javax.swing.JButton jButton_New_Folder;
    private javax.swing.JLabel jLabel_Sidebar_Places;
    private javax.swing.JMenuItem jMenuItem_new_folder;
    private javax.swing.JPanel jPanel_Finder;
    private javax.swing.JPanel jPanel_Finder_Dashboard;
    private javax.swing.JPanel jPanel_Path_bar;
    private javax.swing.JPanel jPanel_Sidebar;
    private javax.swing.JPanel jPanel_Top_Panel;
    private javax.swing.JPanel jPanel_Top_bar;
    private javax.swing.JPopupMenu jPopupMenu_Finder_Options;
    private javax.swing.JScrollPane jScrollPane_Folder_Structure;
    private javax.swing.JTextField jTextField_Path;
    private javax.swing.JTree jTree_Folder_Strcture;
    // End of variables declaration//GEN-END:variables
}
